#pragma once

/***************************************************************
 * This source files comes from the xLights project
 * https://www.xlights.org
 * https://github.com/xLightsSequencer/xLights
 * See the github commit history for a record of contributing
 * developers.
 * Copyright claimed based on commit dates recorded in Github
 * License: https://github.com/xLightsSequencer/xLights/blob/master/License.txt
 **************************************************************/

 //(*Headers(DMXMHPanel)
 #include <wx/panel.h>
 class wxBitmapButton;
 class wxButton;
 class wxCheckBox;
 class wxFlexGridSizer;
 class wxNotebook;
 class wxNotebookEvent;
 class wxSlider;
 class wxStaticText;
 class wxTextCtrl;
 //*)

#include "../BulkEditControls.h"
#include "EffectPanelUtils.h"

class Model;

class DMXMHPanel: public xlEffectPanel
{
	std::list<Model*> GetActiveModels();

	public:

		DMXMHPanel(wxWindow* parent);
		virtual ~DMXMHPanel();
		virtual void ValidateWindow() override;

		//(*Declarations(DMXMHPanel)
		BulkEditCheckBox* CheckBox_INVDMXMH10;
		BulkEditCheckBox* CheckBox_INVDMXMH11;
		BulkEditCheckBox* CheckBox_INVDMXMH12;
		BulkEditCheckBox* CheckBox_INVDMXMH13;
		BulkEditCheckBox* CheckBox_INVDMXMH14;
		BulkEditCheckBox* CheckBox_INVDMXMH15;
		BulkEditCheckBox* CheckBox_INVDMXMH16;
		BulkEditCheckBox* CheckBox_INVDMXMH17;
		BulkEditCheckBox* CheckBox_INVDMXMH18;
		BulkEditCheckBox* CheckBox_INVDMXMH19;
		BulkEditCheckBox* CheckBox_INVDMXMH1;
		BulkEditCheckBox* CheckBox_INVDMXMH20;
		BulkEditCheckBox* CheckBox_INVDMXMH21;
		BulkEditCheckBox* CheckBox_INVDMXMH22;
		BulkEditCheckBox* CheckBox_INVDMXMH23;
		BulkEditCheckBox* CheckBox_INVDMXMH24;
		BulkEditCheckBox* CheckBox_INVDMXMH25;
		BulkEditCheckBox* CheckBox_INVDMXMH26;
		BulkEditCheckBox* CheckBox_INVDMXMH27;
		BulkEditCheckBox* CheckBox_INVDMXMH28;
		BulkEditCheckBox* CheckBox_INVDMXMH29;
		BulkEditCheckBox* CheckBox_INVDMXMH2;
		BulkEditCheckBox* CheckBox_INVDMXMH30;
		BulkEditCheckBox* CheckBox_INVDMXMH31;
		BulkEditCheckBox* CheckBox_INVDMXMH32;
		BulkEditCheckBox* CheckBox_INVDMXMH33;
		BulkEditCheckBox* CheckBox_INVDMXMH34;
		BulkEditCheckBox* CheckBox_INVDMXMH35;
		BulkEditCheckBox* CheckBox_INVDMXMH36;
		BulkEditCheckBox* CheckBox_INVDMXMH37;
		BulkEditCheckBox* CheckBox_INVDMXMH38;
		BulkEditCheckBox* CheckBox_INVDMXMH39;
		BulkEditCheckBox* CheckBox_INVDMXMH3;
		BulkEditCheckBox* CheckBox_INVDMXMH40;
		BulkEditCheckBox* CheckBox_INVDMXMH41;
		BulkEditCheckBox* CheckBox_INVDMXMH42;
		BulkEditCheckBox* CheckBox_INVDMXMH43;
		BulkEditCheckBox* CheckBox_INVDMXMH44;
		BulkEditCheckBox* CheckBox_INVDMXMH45;
		BulkEditCheckBox* CheckBox_INVDMXMH46;
		BulkEditCheckBox* CheckBox_INVDMXMH47;
		BulkEditCheckBox* CheckBox_INVDMXMH48;
		BulkEditCheckBox* CheckBox_INVDMXMH4;
		BulkEditCheckBox* CheckBox_INVDMXMH5;
		BulkEditCheckBox* CheckBox_INVDMXMH6;
		BulkEditCheckBox* CheckBox_INVDMXMH7;
		BulkEditCheckBox* CheckBox_INVDMXMH8;
		BulkEditCheckBox* CheckBox_INVDMXMH9;
		BulkEditSlider* Slider_DMXMH10;
		BulkEditSlider* Slider_DMXMH11;
		BulkEditSlider* Slider_DMXMH12;
		BulkEditSlider* Slider_DMXMH13;
		BulkEditSlider* Slider_DMXMH14;
		BulkEditSlider* Slider_DMXMH15;
		BulkEditSlider* Slider_DMXMH16;
		BulkEditSlider* Slider_DMXMH17;
		BulkEditSlider* Slider_DMXMH18;
		BulkEditSlider* Slider_DMXMH19;
		BulkEditSlider* Slider_DMXMH1;
		BulkEditSlider* Slider_DMXMH20;
		BulkEditSlider* Slider_DMXMH21;
		BulkEditSlider* Slider_DMXMH22;
		BulkEditSlider* Slider_DMXMH23;
		BulkEditSlider* Slider_DMXMH24;
		BulkEditSlider* Slider_DMXMH25;
		BulkEditSlider* Slider_DMXMH26;
		BulkEditSlider* Slider_DMXMH27;
		BulkEditSlider* Slider_DMXMH28;
		BulkEditSlider* Slider_DMXMH29;
		BulkEditSlider* Slider_DMXMH2;
		BulkEditSlider* Slider_DMXMH30;
		BulkEditSlider* Slider_DMXMH31;
		BulkEditSlider* Slider_DMXMH32;
		BulkEditSlider* Slider_DMXMH33;
		BulkEditSlider* Slider_DMXMH34;
		BulkEditSlider* Slider_DMXMH35;
		BulkEditSlider* Slider_DMXMH36;
		BulkEditSlider* Slider_DMXMH37;
		BulkEditSlider* Slider_DMXMH38;
		BulkEditSlider* Slider_DMXMH39;
		BulkEditSlider* Slider_DMXMH3;
		BulkEditSlider* Slider_DMXMH40;
		BulkEditSlider* Slider_DMXMH41;
		BulkEditSlider* Slider_DMXMH42;
		BulkEditSlider* Slider_DMXMH43;
		BulkEditSlider* Slider_DMXMH44;
		BulkEditSlider* Slider_DMXMH45;
		BulkEditSlider* Slider_DMXMH46;
		BulkEditSlider* Slider_DMXMH47;
		BulkEditSlider* Slider_DMXMH48;
		BulkEditSlider* Slider_DMXMH4;
		BulkEditSlider* Slider_DMXMH5;
		BulkEditSlider* Slider_DMXMH6;
		BulkEditSlider* Slider_DMXMH7;
		BulkEditSlider* Slider_DMXMH8;
		BulkEditSlider* Slider_DMXMH9;
		BulkEditValueCurveButton* ValueCurve_DMXMH10;
		BulkEditValueCurveButton* ValueCurve_DMXMH11;
		BulkEditValueCurveButton* ValueCurve_DMXMH12;
		BulkEditValueCurveButton* ValueCurve_DMXMH13;
		BulkEditValueCurveButton* ValueCurve_DMXMH14;
		BulkEditValueCurveButton* ValueCurve_DMXMH15;
		BulkEditValueCurveButton* ValueCurve_DMXMH16;
		BulkEditValueCurveButton* ValueCurve_DMXMH17;
		BulkEditValueCurveButton* ValueCurve_DMXMH18;
		BulkEditValueCurveButton* ValueCurve_DMXMH19;
		BulkEditValueCurveButton* ValueCurve_DMXMH1;
		BulkEditValueCurveButton* ValueCurve_DMXMH20;
		BulkEditValueCurveButton* ValueCurve_DMXMH21;
		BulkEditValueCurveButton* ValueCurve_DMXMH22;
		BulkEditValueCurveButton* ValueCurve_DMXMH23;
		BulkEditValueCurveButton* ValueCurve_DMXMH24;
		BulkEditValueCurveButton* ValueCurve_DMXMH25;
		BulkEditValueCurveButton* ValueCurve_DMXMH26;
		BulkEditValueCurveButton* ValueCurve_DMXMH27;
		BulkEditValueCurveButton* ValueCurve_DMXMH28;
		BulkEditValueCurveButton* ValueCurve_DMXMH29;
		BulkEditValueCurveButton* ValueCurve_DMXMH2;
		BulkEditValueCurveButton* ValueCurve_DMXMH30;
		BulkEditValueCurveButton* ValueCurve_DMXMH31;
		BulkEditValueCurveButton* ValueCurve_DMXMH32;
		BulkEditValueCurveButton* ValueCurve_DMXMH33;
		BulkEditValueCurveButton* ValueCurve_DMXMH34;
		BulkEditValueCurveButton* ValueCurve_DMXMH35;
		BulkEditValueCurveButton* ValueCurve_DMXMH36;
		BulkEditValueCurveButton* ValueCurve_DMXMH37;
		BulkEditValueCurveButton* ValueCurve_DMXMH38;
		BulkEditValueCurveButton* ValueCurve_DMXMH39;
		BulkEditValueCurveButton* ValueCurve_DMXMH3;
		BulkEditValueCurveButton* ValueCurve_DMXMH40;
		BulkEditValueCurveButton* ValueCurve_DMXMH41;
		BulkEditValueCurveButton* ValueCurve_DMXMH42;
		BulkEditValueCurveButton* ValueCurve_DMXMH43;
		BulkEditValueCurveButton* ValueCurve_DMXMH44;
		BulkEditValueCurveButton* ValueCurve_DMXMH45;
		BulkEditValueCurveButton* ValueCurve_DMXMH46;
		BulkEditValueCurveButton* ValueCurve_DMXMH47;
		BulkEditValueCurveButton* ValueCurve_DMXMH48;
		BulkEditValueCurveButton* ValueCurve_DMXMH4;
		BulkEditValueCurveButton* ValueCurve_DMXMH5;
		BulkEditValueCurveButton* ValueCurve_DMXMH6;
		BulkEditValueCurveButton* ValueCurve_DMXMH7;
		BulkEditValueCurveButton* ValueCurve_DMXMH8;
		BulkEditValueCurveButton* ValueCurve_DMXMH9;
		wxButton* ButtonRemap;
		wxButton* Button_Load_State;
		wxButton* Button_SaveAsState;
		wxFlexGridSizer* FlexGridSizer_Main;
		wxFlexGridSizer* FlexGridSizer_Panel1;
		wxFlexGridSizer* FlexGridSizer_Panel2;
		wxFlexGridSizer* FlexGridSizer_Panel3;
		wxNotebook* Notebook7;
		wxPanel* ChannelPanelMH1;
		wxPanel* ChannelPanelMH2;
		wxPanel* ChannelPanelMH3;
		wxStaticText* Label_DMXMH10;
		wxStaticText* Label_DMXMH11;
		wxStaticText* Label_DMXMH12;
		wxStaticText* Label_DMXMH13;
		wxStaticText* Label_DMXMH14;
		wxStaticText* Label_DMXMH15;
		wxStaticText* Label_DMXMH16;
		wxStaticText* Label_DMXMH17;
		wxStaticText* Label_DMXMH18;
		wxStaticText* Label_DMXMH19;
		wxStaticText* Label_DMXMH1;
		wxStaticText* Label_DMXMH20;
		wxStaticText* Label_DMXMH21;
		wxStaticText* Label_DMXMH22;
		wxStaticText* Label_DMXMH23;
		wxStaticText* Label_DMXMH24;
		wxStaticText* Label_DMXMH25;
		wxStaticText* Label_DMXMH26;
		wxStaticText* Label_DMXMH27;
		wxStaticText* Label_DMXMH28;
		wxStaticText* Label_DMXMH29;
		wxStaticText* Label_DMXMH2;
		wxStaticText* Label_DMXMH30;
		wxStaticText* Label_DMXMH31;
		wxStaticText* Label_DMXMH32;
		wxStaticText* Label_DMXMH33;
		wxStaticText* Label_DMXMH34;
		wxStaticText* Label_DMXMH35;
		wxStaticText* Label_DMXMH36;
		wxStaticText* Label_DMXMH37;
		wxStaticText* Label_DMXMH38;
		wxStaticText* Label_DMXMH39;
		wxStaticText* Label_DMXMH3;
		wxStaticText* Label_DMXMH40;
		wxStaticText* Label_DMXMH41;
		wxStaticText* Label_DMXMH42;
		wxStaticText* Label_DMXMH43;
		wxStaticText* Label_DMXMH44;
		wxStaticText* Label_DMXMH45;
		wxStaticText* Label_DMXMH46;
		wxStaticText* Label_DMXMH47;
		wxStaticText* Label_DMXMH48;
		wxStaticText* Label_DMXMH4;
		wxStaticText* Label_DMXMH5;
		wxStaticText* Label_DMXMH6;
		wxStaticText* Label_DMXMH7;
		wxStaticText* Label_DMXMH8;
		wxStaticText* Label_DMXMH9;
		//*)

	protected:

		//(*Identifiers(DMXMHPanel)
		static const wxWindowID ID_STATICTEXT_DMXMH1;
		static const wxWindowID ID_SLIDER_DMXMH1;
		static const wxWindowID ID_VALUECURVE_DMXMH1;
		static const wxWindowID IDD_TEXTCTRL_DMXMH1;
		static const wxWindowID ID_CHECKBOX_INVDMXMH1;
		static const wxWindowID ID_STATICTEXT_DMXMH2;
		static const wxWindowID ID_SLIDER_DMXMH2;
		static const wxWindowID ID_VALUECURVE_DMXMH2;
		static const wxWindowID IDD_TEXTCTRL_DMXMH2;
		static const wxWindowID ID_CHECKBOX_INVDMXMH2;
		static const wxWindowID ID_STATICTEXT_DMXMH3;
		static const wxWindowID ID_SLIDER_DMXMH3;
		static const wxWindowID ID_VALUECURVE_DMXMH3;
		static const wxWindowID IDD_TEXTCTRL_DMXMH3;
		static const wxWindowID ID_CHECKBOX_INVDMXMH3;
		static const wxWindowID ID_STATICTEXT_DMXMH4;
		static const wxWindowID ID_SLIDER_DMXMH4;
		static const wxWindowID ID_VALUECURVE_DMXMH4;
		static const wxWindowID IDD_TEXTCTRL_DMXMH4;
		static const wxWindowID ID_CHECKBOX_INVDMXMH4;
		static const wxWindowID ID_STATICTEXT_DMXMH5;
		static const wxWindowID ID_SLIDER_DMXMH5;
		static const wxWindowID ID_VALUECURVE_DMXMH5;
		static const wxWindowID IDD_TEXTCTRL_DMXMH5;
		static const wxWindowID ID_CHECKBOX_INVDMXMH5;
		static const wxWindowID ID_STATICTEXT_DMXMH6;
		static const wxWindowID ID_SLIDER_DMXMH6;
		static const wxWindowID ID_VALUECURVE_DMXMH6;
		static const wxWindowID IDD_TEXTCTRL_DMXMH6;
		static const wxWindowID ID_CHECKBOX_INVDMXMH6;
		static const wxWindowID ID_STATICTEXT_DMXMH7;
		static const wxWindowID ID_SLIDER_DMXMH7;
		static const wxWindowID ID_VALUECURVE_DMXMH7;
		static const wxWindowID IDD_TEXTCTRL_DMXMH7;
		static const wxWindowID ID_CHECKBOX_INVDMXMH7;
		static const wxWindowID ID_STATICTEXT_DMXMH8;
		static const wxWindowID ID_SLIDER_DMXMH8;
		static const wxWindowID ID_VALUECURVE_DMXMH8;
		static const wxWindowID IDD_TEXTCTRL_DMXMH8;
		static const wxWindowID ID_CHECKBOX_INVDMXMH8;
		static const wxWindowID ID_STATICTEXT_DMXMH9;
		static const wxWindowID ID_SLIDER_DMXMH9;
		static const wxWindowID ID_VALUECURVE_DMXMH9;
		static const wxWindowID IDD_TEXTCTRL_DMXMH9;
		static const wxWindowID ID_CHECKBOX_INVDMXMH9;
		static const wxWindowID ID_STATICTEXT_DMXMH10;
		static const wxWindowID ID_SLIDER_DMXMH10;
		static const wxWindowID ID_VALUECURVE_DMXMH10;
		static const wxWindowID IDD_TEXTCTRL_DMXMH10;
		static const wxWindowID ID_CHECKBOX_INVDMXMH10;
		static const wxWindowID ID_STATICTEXT_DMXMH11;
		static const wxWindowID ID_SLIDER_DMXMH11;
		static const wxWindowID ID_VALUECURVE_DMXMH11;
		static const wxWindowID IDD_TEXTCTRL_DMXMH11;
		static const wxWindowID ID_CHECKBOX_INVDMXMH11;
		static const wxWindowID ID_STATICTEXT_DMXMH12;
		static const wxWindowID ID_SLIDER_DMXMH12;
		static const wxWindowID ID_VALUECURVE_DMXMH12;
		static const wxWindowID IDD_TEXTCTRL_DMXMH12;
		static const wxWindowID ID_CHECKBOX_INVDMXMH12;
		static const wxWindowID ID_STATICTEXT_DMXMH13;
		static const wxWindowID ID_SLIDER_DMXMH13;
		static const wxWindowID ID_VALUECURVE_DMXMH13;
		static const wxWindowID IDD_TEXTCTRL_DMXMH13;
		static const wxWindowID ID_CHECKBOX_INVDMXMH13;
		static const wxWindowID ID_STATICTEXT_DMXMH14;
		static const wxWindowID ID_SLIDER_DMXMH14;
		static const wxWindowID ID_VALUECURVE_DMXMH14;
		static const wxWindowID IDD_TEXTCTRL_DMXMH14;
		static const wxWindowID ID_CHECKBOX_INVDMXMH14;
		static const wxWindowID ID_STATICTEXT_DMXMH15;
		static const wxWindowID ID_SLIDER_DMXMH15;
		static const wxWindowID ID_VALUECURVE_DMXMH15;
		static const wxWindowID IDD_TEXTCTRL_DMXMH15;
		static const wxWindowID ID_CHECKBOX_INVDMXMH15;
		static const wxWindowID ID_STATICTEXT_DMXMH16;
		static const wxWindowID ID_SLIDER_DMXMH16;
		static const wxWindowID ID_VALUECURVE_DMXMH16;
		static const wxWindowID IDD_TEXTCTRL_DMXMH16;
		static const wxWindowID ID_CHECKBOX_INVDMXMH16;
		static const wxWindowID ID_PANEL6;
		static const wxWindowID ID_STATICTEXT_DMXMH17;
		static const wxWindowID ID_SLIDER_DMXMH17;
		static const wxWindowID ID_VALUECURVE_DMXMH17;
		static const wxWindowID IDD_TEXTCTRL_DMXMH17;
		static const wxWindowID ID_CHECKBOX_INVDMXMH17;
		static const wxWindowID ID_STATICTEXT_DMXMH18;
		static const wxWindowID ID_SLIDER_DMXMH18;
		static const wxWindowID ID_VALUECURVE_DMXMH18;
		static const wxWindowID IDD_TEXTCTRL_DMXMH18;
		static const wxWindowID ID_CHECKBOX_INVDMXMH18;
		static const wxWindowID ID_STATICTEXT_DMXMH19;
		static const wxWindowID ID_SLIDER_DMXMH19;
		static const wxWindowID ID_VALUECURVE_DMXMH19;
		static const wxWindowID IDD_TEXTCTRL_DMXMH19;
		static const wxWindowID ID_CHECKBOX_INVDMXMH19;
		static const wxWindowID ID_STATICTEXT_DMXMH20;
		static const wxWindowID ID_SLIDER_DMXMH20;
		static const wxWindowID ID_VALUECURVE_DMXMH20;
		static const wxWindowID IDD_TEXTCTRL_DMXMH20;
		static const wxWindowID ID_CHECKBOX_INVDMXMH20;
		static const wxWindowID ID_STATICTEXT_DMXMH21;
		static const wxWindowID ID_SLIDER_DMXMH21;
		static const wxWindowID ID_VALUECURVE_DMXMH21;
		static const wxWindowID IDD_TEXTCTRL_DMXMH21;
		static const wxWindowID ID_CHECKBOX_INVDMXMH21;
		static const wxWindowID ID_STATICTEXT_DMXMH22;
		static const wxWindowID ID_SLIDER_DMXMH22;
		static const wxWindowID ID_VALUECURVE_DMXMH22;
		static const wxWindowID IDD_TEXTCTRL_DMXMH22;
		static const wxWindowID ID_CHECKBOX_INVDMXMH22;
		static const wxWindowID ID_STATICTEXT_DMXMH23;
		static const wxWindowID ID_SLIDER_DMXMH23;
		static const wxWindowID ID_VALUECURVE_DMXMH23;
		static const wxWindowID IDD_TEXTCTRL_DMXMH23;
		static const wxWindowID ID_CHECKBOX_INVDMXMH23;
		static const wxWindowID ID_STATICTEXT_DMXMH24;
		static const wxWindowID ID_SLIDER_DMXMH24;
		static const wxWindowID ID_VALUECURVE_DMXMH24;
		static const wxWindowID IDD_TEXTCTRL_DMXMH24;
		static const wxWindowID ID_CHECKBOX_INVDMXMH24;
		static const wxWindowID ID_STATICTEXT_DMXMH25;
		static const wxWindowID ID_SLIDER_DMXMH25;
		static const wxWindowID ID_VALUECURVE_DMXMH25;
		static const wxWindowID IDD_TEXTCTRL_DMXMH25;
		static const wxWindowID ID_CHECKBOX_INVDMXMH25;
		static const wxWindowID ID_STATICTEXT_DMXMH26;
		static const wxWindowID ID_SLIDER_DMXMH26;
		static const wxWindowID ID_VALUECURVE_DMXMH26;
		static const wxWindowID IDD_TEXTCTRL_DMXMH26;
		static const wxWindowID ID_CHECKBOX_INVDMXMH26;
		static const wxWindowID ID_STATICTEXT_DMXMH27;
		static const wxWindowID ID_SLIDER_DMXMH27;
		static const wxWindowID ID_VALUECURVE_DMXMH27;
		static const wxWindowID IDD_TEXTCTRL_DMXMH27;
		static const wxWindowID ID_CHECKBOX_INVDMXMH27;
		static const wxWindowID ID_STATICTEXT_DMXMH28;
		static const wxWindowID ID_SLIDER_DMXMH28;
		static const wxWindowID ID_VALUECURVE_DMXMH28;
		static const wxWindowID IDD_TEXTCTRL_DMXMH28;
		static const wxWindowID ID_CHECKBOX_INVDMXMH28;
		static const wxWindowID ID_STATICTEXT_DMXMH29;
		static const wxWindowID ID_SLIDER_DMXMH29;
		static const wxWindowID ID_VALUECURVE_DMXMH29;
		static const wxWindowID IDD_TEXTCTRL_DMXMH29;
		static const wxWindowID ID_CHECKBOX_INVDMXMH29;
		static const wxWindowID ID_STATICTEXT_DMXMH30;
		static const wxWindowID ID_SLIDER_DMXMH30;
		static const wxWindowID ID_VALUECURVE_DMXMH30;
		static const wxWindowID IDD_TEXTCTRL_DMXMH30;
		static const wxWindowID ID_CHECKBOX_INVDMXMH30;
		static const wxWindowID ID_STATICTEXT_DMXMH31;
		static const wxWindowID ID_SLIDER_DMXMH31;
		static const wxWindowID ID_VALUECURVE_DMXMH31;
		static const wxWindowID IDD_TEXTCTRL_DMXMH31;
		static const wxWindowID ID_CHECKBOX_INVDMXMH31;
		static const wxWindowID ID_STATICTEXT_DMXMH32;
		static const wxWindowID ID_SLIDER_DMXMH32;
		static const wxWindowID ID_VALUECURVE_DMXMH32;
		static const wxWindowID IDD_TEXTCTRL_DMXMH32;
		static const wxWindowID ID_CHECKBOX_INVDMXMH32;
		static const wxWindowID ID_PANEL28;
		static const wxWindowID ID_STATICTEXT_DMXMH33;
		static const wxWindowID ID_SLIDER_DMXMH33;
		static const wxWindowID ID_VALUECURVE_DMXMH33;
		static const wxWindowID IDD_TEXTCTRL_DMXMH33;
		static const wxWindowID ID_CHECKBOX_INVDMXMH33;
		static const wxWindowID ID_STATICTEXT_DMXMH34;
		static const wxWindowID ID_SLIDER_DMXMH34;
		static const wxWindowID ID_VALUECURVE_DMXMH34;
		static const wxWindowID IDD_TEXTCTRL_DMXMH34;
		static const wxWindowID ID_CHECKBOX_INVDMXMH34;
		static const wxWindowID ID_STATICTEXT_DMXMH35;
		static const wxWindowID ID_SLIDER_DMXMH35;
		static const wxWindowID ID_VALUECURVE_DMXMH35;
		static const wxWindowID IDD_TEXTCTRL_DMXMH35;
		static const wxWindowID ID_CHECKBOX_INVDMXMH35;
		static const wxWindowID ID_STATICTEXT_DMXMH36;
		static const wxWindowID ID_SLIDER_DMXMH36;
		static const wxWindowID ID_VALUECURVE_DMXMH36;
		static const wxWindowID IDD_TEXTCTRL_DMXMH36;
		static const wxWindowID ID_CHECKBOX_INVDMXMH36;
		static const wxWindowID ID_STATICTEXT_DMXMH37;
		static const wxWindowID ID_SLIDER_DMXMH37;
		static const wxWindowID ID_VALUECURVE_DMXMH37;
		static const wxWindowID IDD_TEXTCTRL_DMXMH37;
		static const wxWindowID ID_CHECKBOX_INVDMXMH37;
		static const wxWindowID ID_STATICTEXT_DMXMH38;
		static const wxWindowID ID_SLIDER_DMXMH38;
		static const wxWindowID ID_VALUECURVE_DMXMH38;
		static const wxWindowID IDD_TEXTCTRL_DMXMH38;
		static const wxWindowID ID_CHECKBOX_INVDMXMH38;
		static const wxWindowID ID_STATICTEXT_DMXMH39;
		static const wxWindowID ID_SLIDER_DMXMH39;
		static const wxWindowID ID_VALUECURVE_DMXMH39;
		static const wxWindowID IDD_TEXTCTRL_DMXMH39;
		static const wxWindowID ID_CHECKBOX_INVDMXMH39;
		static const wxWindowID ID_STATICTEXT_DMXMH40;
		static const wxWindowID ID_SLIDER_DMXMH40;
		static const wxWindowID ID_VALUECURVE_DMXMH40;
		static const wxWindowID IDD_TEXTCTRL_DMXMH40;
		static const wxWindowID ID_CHECKBOX_INVDMXMH40;
		static const wxWindowID ID_STATICTEXT_DMXMH41;
		static const wxWindowID ID_SLIDER_DMXMH41;
		static const wxWindowID ID_VALUECURVE_DMXMH41;
		static const wxWindowID IDD_TEXTCTRL_DMXMH41;
		static const wxWindowID ID_CHECKBOX_INVDMXMH41;
		static const wxWindowID ID_STATICTEXT_DMXMH42;
		static const wxWindowID ID_SLIDER_DMXMH42;
		static const wxWindowID ID_VALUECURVE_DMXMH42;
		static const wxWindowID IDD_TEXTCTRL_DMXMH42;
		static const wxWindowID ID_CHECKBOX_INVDMXMH42;
		static const wxWindowID ID_STATICTEXT_DMXMH43;
		static const wxWindowID ID_SLIDER_DMXMH43;
		static const wxWindowID ID_VALUECURVE_DMXMH43;
		static const wxWindowID IDD_TEXTCTRL_DMXMH43;
		static const wxWindowID ID_CHECKBOX_INVDMXMH43;
		static const wxWindowID ID_STATICTEXT_DMXMH44;
		static const wxWindowID ID_SLIDER_DMXMH44;
		static const wxWindowID ID_VALUECURVE_DMXMH44;
		static const wxWindowID IDD_TEXTCTRL_DMXMH44;
		static const wxWindowID ID_CHECKBOX_INVDMXMH44;
		static const wxWindowID ID_STATICTEXT_DMXMH45;
		static const wxWindowID ID_SLIDER_DMXMH45;
		static const wxWindowID ID_VALUECURVE_DMXMH45;
		static const wxWindowID IDD_TEXTCTRL_DMXMH45;
		static const wxWindowID ID_CHECKBOX_INVDMXMH45;
		static const wxWindowID ID_STATICTEXT_DMXMH46;
		static const wxWindowID ID_SLIDER_DMXMH46;
		static const wxWindowID ID_VALUECURVE_DMXMH46;
		static const wxWindowID IDD_TEXTCTRL_DMXMH46;
		static const wxWindowID ID_CHECKBOX_INVDMXMH46;
		static const wxWindowID ID_STATICTEXT_DMXMH47;
		static const wxWindowID ID_SLIDER_DMXMH47;
		static const wxWindowID ID_VALUECURVE_DMXMH47;
		static const wxWindowID IDD_TEXTCTRL_DMXMH47;
		static const wxWindowID ID_CHECKBOX_INVDMXMH47;
		static const wxWindowID ID_STATICTEXT_DMXMH48;
		static const wxWindowID ID_SLIDER_DMXMH48;
		static const wxWindowID ID_VALUECURVE_DMXMH48;
		static const wxWindowID IDD_TEXTCTRL_DMXMH48;
		static const wxWindowID ID_CHECKBOX_INVDMXMH48;
		static const wxWindowID ID_PANEL3;
		static const wxWindowID ID_NOTEBOOK1;
		static const wxWindowID ID_BUTTON1;
		static const wxWindowID ID_BUTTON2;
		static const wxWindowID ID_BUTTON_LOAD_STATE;
		//*)

	public:

		//(*Handlers(DMXMHPanel)
		void OnButtonRemapClick(wxCommandEvent& event);
		void OnButton_SaveAsStateClick(wxCommandEvent& event);
		void OnButton_Load_StateClick(wxCommandEvent& event);
		void OnNotebook7PageChanged(wxNotebookEvent& event);
		//*)

        void OnButtonRemapRClick(wxCommandEvent& event);
        void OnChoicePopup(wxCommandEvent& event);

    DECLARE_EVENT_TABLE()
};
